pub const LEFT_ANGLE_BRACKET: char = '<';
pub const RIGHT_ANGLE_BRACKET: char = '>';
pub const OPENING_BRACE: char = '{';
pub const CLOSING_BRACE: char = '}';
pub const SINGLE_QUOTE: char = '\'';
pub const DOUBLE_QUOTE: char = '"';
pub const COLON: char = ':';
pub const HASH: char = '#';
pub const DASH: char = '-';
pub const DOT: char = '.';
pub const PERCENT: char = '%';
pub const SEMICOLON: char = ';';
pub const EXCLAMATION_MARK: char = '!';
pub const SLASH: char = '/';
pub const EQUALS: char = '=';
pub const WHITESPACE: char = ' ';